# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNLocalization' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNLocalization

  target 'RNLocalization-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNLanguages', :path => '../node_modules/react-native-languages'

  end

  target 'RNLocalizationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNLocalization-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNLocalization-tvOS

 # target 'RNLocalization-tvOSTests' do
   # inherit! :search_paths
    # Pods for testing
  #end

end
